version: '3.6'
services:
  nginx:
    image: ${REPOSITORY:-localhost:5000}/nginx:${NGINX_VER:-mainline}
    ports:
    - 8080:8080
    volumes:
    - ./html-vol:/usr/share/nginx/html
    - ./conf.d:/etc/nginx/conf.d
    # start as root to automatically correct user permissions
    user: "0:0"
