version: '3.6'
services:
  nginx:
    image: ${REPOSITORY:-localhost:5000}/nginx:${NGINX_VER:-mainline}
    ports:
    - 8080:8080
    volumes:
    - type: tmpfs
      target: /usr/share/nginx/html
    - type: bind
      source: ./conf.d
      target: /etc/nginx/conf.d
      read_only: true
    # start as root to automatically correct user permissions
    user: "0:0"
    # tty needed to have stdout permissions 
    tty: true
